### ISSUE TITLE
bintray ospos bang

### ISSUE THREAD

**Issue by andriux1990** [opensourcepos/opensourcepos#2737]
Symfony and vlucas directories are not in this version.
so autoload.php have also changed in vendor directory and composer directory files

**Comment by jekkos** [comment]
that's because I change the line to only install non dev dependencies. 
If you expect them to be in there then those dependencies are declared in the wrong place.

**Comment by andriux1990** [comment]
from here I have downloaded them https://bintray.com/jekkos/opensourcepos/opensourcepos#files

**Comment by mckaygerhard** [comment]
seeem he are talking about bintray @jekkos ...  do you noted he never used directly the github files? puff...

**Comment by andriux1990** [comment]
> seeem he are talking about bintray @jekkos ... do you noted he never used directly the github files? puff...

so is. I always use bintray

**Comment by jekkos** [comment]
Ok yes that's clear @andriux1990. I wonder do you need the dotenv? I would guess it's only useful for development?

**Comment by andriux1990** [comment]
I don't know if I'm wrong. but the bintray ospos is ready to be installed.
the problem is that these new versions I can not make them work on my computer

**Comment by daN4cat** [comment]
What is that doesn't work? Can you be more precise?

**Comment by andriux1990** [comment]
> What is that doesn't work? Can you be more precise?

after unzipping the version that you downloaded from bintray and set database.php to connect to my database. Then I go to the browser and open the site. i have error "This non-functional page host cannot process this request at this time."

I don't know if this happens to me alone, or I have to make extra settings on my computer. because if I replace the seller folder with an earlier version of one that works, there if I no longer have the 500 error and I can use ospos

**Comment by odiea** [comment]
Indeed there is an issue with the new bintray files. Will not load anything.

**Comment by odiea** [comment]
It loads properly after you comment out the following in config/hooks
```
$hook['pre_system'] = function() {
    $config_path = APPPATH . 'config/';
	try {
		$dotenv = new Dotenv\Dotenv($config_path);
		$dotenv->overload();
	} catch(Exception $e) {
		// continue, .env file not present
	}
};

**Comment by jekkos** [comment]
Ok thanks @odiea for clarification. I guess the dotenv dependency is in the wrong place then, will add it to the production deps now.

**Comment by jekkos** [comment]
Should be fixed now.

**Comment by odiea** [comment]
I downloaded the following and still get the following error.
https://bintray.com/jekkos/opensourcepos/download_file?file_path=opensourcepos.20200226231825.multistage-docker.123f4c.zip
Filename: C:\wamp64\www\today\application\config\hooks.php

An uncaught Exception was encountered
Type: Error

Message: Class 'Dotenv\Dotenv' not found


Line Number: 32

Backtrace:

File: C:\wamp64\www\today\public\index.php
Line: 315
Function: require_once

**Comment by jekkos** [comment]
Thanks for testing! I did two commits actually, this one is the first (amended and overwrote it in fact). So you'll need to find the build for `b8174a85eeff0c7a5c760050de57c126cf342a1a` instead

**Comment by odiea** [comment]
I tried that build also and got the same result. Will try again tomorrow.

**Comment by odiea** [comment]
An uncaught Exception was encountered
Type: Error

Message: Class 'Dotenv\Dotenv' not found

Filename: C:\wamp64\www\today\application\config\hooks.php

Line Number: 32

Backtrace:

File: C:\wamp64\www\today\public\index.php
Line: 315
Function: require_once

**Comment by odiea** [comment]
@jekkos I still got the above issue in my last test. How about reverting the following commit.
commit 556335918b684214601edf8d9f5ce1f848ba3427 to see if that is the issue.

**Comment by odiea** [comment]
@jekkos It works again after your last commit. Thanks. You might want to delete the older master files now to prevent further issues if someone decides to download from Bintray .

**Comment by odiea** [comment]
This issue has been solved. Now in Bintray unstable. So I will close it.
