### ISSUE TITLE
Call to undefined function bcscale() IN NGINX Installation

### ISSUE THREAD

**Issue by gkapaino** [opensourcepos/opensourcepos#2789]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

An uncaught Exception was encountered
Type: Error

Message: Call to undefined function bcscale()

Filename: /var/www/html/kibahaonline/pos/application/hooks/load_config.php

Line Number: 42

Backtrace:

File: /var/www/html/kibahaonline/pos/public/index.php
Line: 315
Function: require_once

**Comment by gkapaino** [comment]
An uncaught Exception was encountered
Type: Error

Message: Call to undefined function bcscale()

Filename: /var/www/html/kibahaonline/pos/application/hooks/load_config.php

Line Number: 42

Backtrace:

File: /var/www/html/kibahaonline/pos/public/index.php
Line: 315
Function: require_once

**Comment by gkapaino** [comment]
solved by install bcmath in php.ini

**Comment by sabetech** [comment]
I have installed bcmath on my Apache server and restarted apache2 but I'm still getting the exact same error specified above.

PHP_VERSION: php7.4
OS: Ubuntu 16.06LTS

**Comment by odiea** [comment]
You might check and see if your version of Apache supports php7.4

**Comment by daN4cat** [comment]
@sabetech you need bcmath for php 7.4. Check that's installed.

**Comment by sabetech** [comment]
> @sabetech you need bcmath for php 7.4. Check that's installed.

Interestingly, when I find out the modules I have with php -m bcmath is not included in the list of modules even though I installed it with `sudo apt-get install php-bcmath`. When I install it, it tells me `php-bcmath is already the newest version (1:7.0+35ubuntu6.1)`. When I do `sudo a2enmod php-bcmath`,  it says `Module php-bcmath does not exist` .

What am I missing here?
