### ISSUE TITLE
CI4 Branch Register issues.

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#3883]
Once I got the gets and posts figured out and the int and strings figured out I have the following issues.
Adding a New Item or a New Customer does not append to the Register.
Item Kits cannot be added and Returns cannot be Returned. Something to do with the pos or kit being there. 
@objecttothis thanks for all the time spent getting us this far on the CI4 upgrade.

**Comment by objecttothis** [comment]
With pleasure. I'm investigating the attributes problems but I can look into this next if someone else doesn't pick it up.

**Comment by odiea** [comment]
Adding a New Item or a New Customer does not append to the Register. This is now working after getting the toast notification to show.

**Comment by objecttothis** [comment]
@odiea can you commit these changes to the branch?

**Comment by odiea** [comment]
I will try to figure out how to do a pull request from git ext. I don't want to fubar the branch.

**Comment by objecttothis** [comment]
You can create a branch from ci4_branch and then after making changes and testing them just create a pull request in github to merge that branch into ci4_branch and we can look at it to make sure no fubaring happens.

**Comment by objecttothis** [comment]
@odiea I just pushed several commits, but one of them hopefully should bring some improvements to the getSearch() functions.  I didn't look at your previous post very carefully.  I see now that this is the exists() function.  I'm guessing it's a similar problem. See if my changes fix the error.

**Comment by odiea** [comment]
No change. I still receive the following error when trying to Return a pos. Thanks for the updates today.

CRITICAL - 2023-12-01 14:03:47 --> Argument 1 passed to App\Models\Sale::exists() must be of the type int, string given, called in C:\wamp64\www\ci4_go\app\Models\Sale.php on line 526
in APPPATH\Models\Sale.php on line 547.
 1 APPPATH\Models\Sale.php(526): App\Models\Sale->exists('')
 2 APPPATH\Controllers\Sales.php(157): App\Models\Sale->is_valid_receipt('pos ')
 3 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Sales->getItemSearch()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Sales))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()

**Comment by objecttothis** [comment]
On line 2 of the stack trace `is_valid_receipt` is being called with `'pos '` which tells me that `$receipt` on line 157 in the sales controller doesn't have the receipt number. Someone will need to trace that back from the view to make sure it's being generated correctly.

**Comment by odiea** [comment]
This again was an issue created by me. At some time in sales controller on line 482 I added (int) and this was causing my issue.

**Comment by odiea** [comment]
It has been years since I created a branch When I tried to create the new ci4_branch  it asks what repository to clone I used
the following https://github.com/opensourcepos/opensourcepos/tree/ci4-branch and it stated it was not a valid repository.

**Comment by objecttothis** [comment]
@odiea you can login to the GitHub site, you can edit a file and when you go to save it will give you the opportunity to create a branch. That's the most straightforward.

**Comment by odiea** [comment]
Thanks I finally figured it out. branch is ci4_branch not ci4_branch. It now shows in my github repository
